version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: smartcampusdb
    ports:
      - "3306:3306"

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/smartcampusdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
    depends_on:
      - db
    ports:
      - "8080:8080"
